permalink: /:year-:month-:day-:title
exclude: [ README.md, CONTRIBUTING.md, CNAME, Gemfile, Gemfile.lock, vendor ]

site:
  title: Photos of Blacklion
  url: http://photosofblacklion.net

plugins:
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "gallery"
      custom_js:
        - "blueimp-gallery.min"
        - "gallery"
