permalink: /albums/:year-:month-:day-:title
exclude: [ README.md, CONTRIBUTING.md, CNAME, Gemfile, Gemfile.lock, _albums ]

site:
  title: Photos of Blacklion
  url: http://photosofblacklion.net

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "gallery"
